#Shimeji-ee Configuration Options
#Mon Apr 13 13:37:09 HST 2026
ActiveShimeji=Sephiroth/Miko/Eevee_Egg/Mosscreep (Orange)/Mossfly (Orange)/Cloud2/mario/Holo/Hornet/2B/CampfireOFF/Cyan/Honduran White Bat/Mosscreep (White)/Mossfly (White)/Zorua_Egg/Grass
AlwaysOnTopDebugWindow=true
AlwaysShowInformationScreen=false
AlwaysShowShimejiChooser=false
Breeding=false
Breeding.imageset.2B=false
Breeding.imageset.CampfireOFF=false
Breeding.imageset.CampfireON=false
Breeding.imageset.CampfireON_blue=false
Breeding.imageset.Cloud2=false
Breeding.imageset.Cyan=false
Breeding.imageset.Eevee_Egg=false
Breeding.imageset.Eevee_Female=false
Breeding.imageset.Eevee_Female_Shiny=false
Breeding.imageset.Eevee_Male=false
Breeding.imageset.Eevee_Male_Shiny=false
Breeding.imageset.Espeon=false
Breeding.imageset.Espeon_Shiny=false
Breeding.imageset.Espeon_ShinyGold=false
Breeding.imageset.Grass=false
Breeding.imageset.Holo=false
Breeding.imageset.Honduran\ White\ Bat=false
Breeding.imageset.Hornet=false
Breeding.imageset.Miko=false
Breeding.imageset.Mosscreep\ (Orange)=true
Breeding.imageset.Mosscreep\ (White)=true
Breeding.imageset.Mossfly\ (Orange)=true
Breeding.imageset.Mossfly\ (White)=true
Breeding.imageset.Paper\ bowser=false
Breeding.imageset.Paper\ mario=false
Breeding.imageset.Sephiroth=false
Breeding.imageset.Sylveon=false
Breeding.imageset.Sylveon_Shiny=false
Breeding.imageset.Umbreon=false
Breeding.imageset.Umbreon_Shiny=false
Breeding.imageset.Zorua=false
Breeding.imageset.Zorua_Egg=false
Breeding.imageset.Zorua_Shiny=false
Breeding.imageset.mario=false
Breeding.imageset.paper\ peach=false
DisabledBehaviours.Grass=PersonalSpace
Environment=generic
Filter=bicubic
Filter.imageset.mario=false
InformationDismissed=CampfireOFF
InteractiveWindows=a/e/i/o/u/Toy Box/File Explorer/Notepad
InteractiveWindowsBlacklist=
MenuDPI=96
Multiscreen=true
Multiscreen.imageset.2B=true
Multiscreen.imageset.CampfireOFF=true
Multiscreen.imageset.CampfireON=true
Multiscreen.imageset.CampfireON_blue=true
Multiscreen.imageset.Cloud2=true
Multiscreen.imageset.Cyan=true
Multiscreen.imageset.Eevee_Egg=true
Multiscreen.imageset.Eevee_Female=true
Multiscreen.imageset.Eevee_Female_Shiny=true
Multiscreen.imageset.Eevee_Male=true
Multiscreen.imageset.Eevee_Male_Shiny=true
Multiscreen.imageset.Espeon=true
Multiscreen.imageset.Espeon_Shiny=true
Multiscreen.imageset.Espeon_ShinyGold=true
Multiscreen.imageset.Grass=true
Multiscreen.imageset.Holo=true
Multiscreen.imageset.Honduran\ White\ Bat=true
Multiscreen.imageset.Hornet=true
Multiscreen.imageset.Miko=true
Multiscreen.imageset.Mosscreep\ (Orange)=true
Multiscreen.imageset.Mosscreep\ (White)=true
Multiscreen.imageset.Mossfly\ (Orange)=true
Multiscreen.imageset.Mossfly\ (White)=true
Multiscreen.imageset.Paper\ bowser=true
Multiscreen.imageset.Paper\ mario=true
Multiscreen.imageset.Sephiroth=true
Multiscreen.imageset.Sylveon=true
Multiscreen.imageset.Sylveon_Shiny=true
Multiscreen.imageset.Umbreon=true
Multiscreen.imageset.Umbreon_Shiny=true
Multiscreen.imageset.Zorua=true
Multiscreen.imageset.Zorua_Egg=true
Multiscreen.imageset.Zorua_Shiny=true
Multiscreen.imageset.mario=true
Multiscreen.imageset.paper\ peach=true
Opacity=1.0
Scale.AlipheeseClothed=1.1
Scale.CampfireOFF=1.1320000000000001
Scale.CampfireON=2.1093008884372484
Scale.CampfireON_blue=1.363924741291708
Scale.Cyan=0.9600000000000002
Scale.Eevee_Egg=0.8
Scale.Eevee_Female=0.8
Scale.Eevee_Female_Shiny=0.8
Scale.Eevee_Male=0.8
Scale.Eevee_Male_Shiny=0.8
Scale.Espeon=0.8
Scale.Espeon_Shiny=0.8
Scale.Espeon_ShinyGold=0.8
Scale.Holo=1.1
Scale.Honduran\ White\ Bat=0.7
Scale.Sephiroth=1.3
Scale.Sylveon=0.8
Scale.Sylveon_Shiny=0.8
Scale.Tamamo=1.1
Scale.Umbreon=0.8
Scale.Umbreon_Shiny=0.8
Scale.Zorua=0.8
Scale.Zorua_Egg=0.8
Scale.Zorua_Shiny=0.8
Scale.mario=1.9
Scaling=0.5
Sounds.imageset.2B=true
Sounds.imageset.CampfireOFF=true
Sounds.imageset.CampfireON=true
Sounds.imageset.CampfireON_blue=true
Sounds.imageset.Cloud2=true
Sounds.imageset.Cyan=true
Sounds.imageset.Eevee_Egg=true
Sounds.imageset.Eevee_Female=true
Sounds.imageset.Eevee_Female_Shiny=true
Sounds.imageset.Eevee_Male=true
Sounds.imageset.Eevee_Male_Shiny=true
Sounds.imageset.Espeon=true
Sounds.imageset.Espeon_Shiny=true
Sounds.imageset.Espeon_ShinyGold=true
Sounds.imageset.Grass=true
Sounds.imageset.Holo=true
Sounds.imageset.Honduran\ White\ Bat=true
Sounds.imageset.Hornet=true
Sounds.imageset.Miko=true
Sounds.imageset.Mosscreep\ (Orange)=true
Sounds.imageset.Mosscreep\ (White)=true
Sounds.imageset.Mossfly\ (Orange)=true
Sounds.imageset.Mossfly\ (White)=true
Sounds.imageset.Paper\ bowser=true
Sounds.imageset.Paper\ mario=true
Sounds.imageset.Sephiroth=true
Sounds.imageset.Sylveon=true
Sounds.imageset.Sylveon_Shiny=true
Sounds.imageset.Umbreon=true
Sounds.imageset.Umbreon_Shiny=true
Sounds.imageset.Zorua=true
Sounds.imageset.Zorua_Egg=true
Sounds.imageset.Zorua_Shiny=true
Sounds.imageset.mario=true
Sounds.imageset.paper\ peach=true
Throwing=false
Throwing.imageset.2B=false
Throwing.imageset.CampfireOFF=false
Throwing.imageset.CampfireON=false
Throwing.imageset.CampfireON_blue=false
Throwing.imageset.Cloud2=false
Throwing.imageset.Cyan=false
Throwing.imageset.Eevee_Egg=false
Throwing.imageset.Eevee_Female=false
Throwing.imageset.Eevee_Female_Shiny=false
Throwing.imageset.Eevee_Male=false
Throwing.imageset.Eevee_Male_Shiny=false
Throwing.imageset.Espeon=false
Throwing.imageset.Espeon_Shiny=false
Throwing.imageset.Espeon_ShinyGold=false
Throwing.imageset.Grass=false
Throwing.imageset.Holo=false
Throwing.imageset.Honduran\ White\ Bat=false
Throwing.imageset.Hornet=false
Throwing.imageset.Miko=false
Throwing.imageset.Mosscreep\ (Orange)=false
Throwing.imageset.Mosscreep\ (White)=false
Throwing.imageset.Mossfly\ (Orange)=false
Throwing.imageset.Mossfly\ (White)=false
Throwing.imageset.Paper\ bowser=false
Throwing.imageset.Paper\ mario=false
Throwing.imageset.Sephiroth=false
Throwing.imageset.Sylveon=false
Throwing.imageset.Sylveon_Shiny=false
Throwing.imageset.Umbreon=false
Throwing.imageset.Umbreon_Shiny=false
Throwing.imageset.Zorua=false
Throwing.imageset.Zorua_Egg=false
Throwing.imageset.Zorua_Shiny=false
Throwing.imageset.mario=false
Throwing.imageset.paper\ peach=false
Transformation.imageset.2B=true
Transformation.imageset.CampfireOFF=true
Transformation.imageset.CampfireON=true
Transformation.imageset.CampfireON_blue=true
Transformation.imageset.Cloud2=true
Transformation.imageset.Cyan=true
Transformation.imageset.Eevee_Egg=true
Transformation.imageset.Eevee_Female=true
Transformation.imageset.Eevee_Female_Shiny=true
Transformation.imageset.Eevee_Male=true
Transformation.imageset.Eevee_Male_Shiny=true
Transformation.imageset.Espeon=true
Transformation.imageset.Espeon_Shiny=true
Transformation.imageset.Espeon_ShinyGold=true
Transformation.imageset.Grass=true
Transformation.imageset.Holo=true
Transformation.imageset.Honduran\ White\ Bat=true
Transformation.imageset.Hornet=true
Transformation.imageset.Miko=true
Transformation.imageset.Mosscreep\ (Orange)=true
Transformation.imageset.Mosscreep\ (White)=true
Transformation.imageset.Mossfly\ (Orange)=true
Transformation.imageset.Mossfly\ (White)=true
Transformation.imageset.Paper\ bowser=true
Transformation.imageset.Paper\ mario=true
Transformation.imageset.Sephiroth=true
Transformation.imageset.Sylveon=true
Transformation.imageset.Sylveon_Shiny=true
Transformation.imageset.Umbreon=true
Transformation.imageset.Umbreon_Shiny=true
Transformation.imageset.Zorua=true
Transformation.imageset.Zorua_Egg=true
Transformation.imageset.Zorua_Shiny=true
Transformation.imageset.mario=true
Transformation.imageset.paper\ peach=true
Transients.imageset.2B=true
Transients.imageset.CampfireOFF=true
Transients.imageset.CampfireON=true
Transients.imageset.CampfireON_blue=true
Transients.imageset.Cloud2=true
Transients.imageset.Cyan=true
Transients.imageset.Eevee_Egg=true
Transients.imageset.Eevee_Female=true
Transients.imageset.Eevee_Female_Shiny=true
Transients.imageset.Eevee_Male=true
Transients.imageset.Eevee_Male_Shiny=true
Transients.imageset.Espeon=true
Transients.imageset.Espeon_Shiny=true
Transients.imageset.Espeon_ShinyGold=true
Transients.imageset.Grass=true
Transients.imageset.Holo=true
Transients.imageset.Honduran\ White\ Bat=true
Transients.imageset.Hornet=true
Transients.imageset.Miko=true
Transients.imageset.Mosscreep\ (Orange)=true
Transients.imageset.Mosscreep\ (White)=true
Transients.imageset.Mossfly\ (Orange)=true
Transients.imageset.Mossfly\ (White)=true
Transients.imageset.Paper\ bowser=true
Transients.imageset.Paper\ mario=true
Transients.imageset.Sephiroth=true
Transients.imageset.Sylveon=true
Transients.imageset.Sylveon_Shiny=true
Transients.imageset.Umbreon=true
Transients.imageset.Umbreon_Shiny=true
Transients.imageset.Zorua=true
Transients.imageset.Zorua_Egg=true
Transients.imageset.Zorua_Shiny=true
Transients.imageset.mario=true
Transients.imageset.paper\ peach=true
