#Shimeji-ee Configuration Options
#Sat Apr 11 22:49:53 HST 2026
ActiveShimeji=Sephiroth/Miko/Eevee_Egg/Mosscreep (Orange)/Mossfly (Orange)/Cloud2/Holo/Hornet/2B/CampfireOFF/Cyan/Honduran White Bat/Mosscreep (White)/Mossfly (White)/Zorua_Egg/Grass
AlwaysOnTopDebugWindow=true
AlwaysShowInformationScreen=false
AlwaysShowShimejiChooser=false
Breeding=false
Breeding.imageset.Mosscreep\ (Orange)=true
Breeding.imageset.Mosscreep\ (White)=true
Breeding.imageset.Mossfly\ (Orange)=true
Breeding.imageset.Mossfly\ (White)=true
DisabledBehaviours.Grass=PersonalSpace
DisabledBehaviours.imageset.Eevee_Female_Shiny=InspectGrassAndEvolveIntoSylveon\!/InspectGrassAndEvolveIntoEspeon\!
Environment=generic
Filter=bicubic
InformationDismissed=CampfireOFF
InteractiveWindows=a/e/i/o/u/Toy Box/File Explorer/Notepad
InteractiveWindowsBlacklist=
MenuDPI=96
Multiscreen=true
Opacity=1.0
Scale.AlipheeseClothed=1.1600000000000001
Scale.CampfireOFF=1.11
Scale.CampfireON=1.1756000000000002
Scale.CampfireON_blue=1.212
Scale.Cyan=0.8480443892802544
Scale.Eevee_Egg=0.8399999999999999
Scale.Eevee_Female=0.8399999999999999
Scale.Eevee_Female_Shiny=0.8399999999999999
Scale.Eevee_Male=0.8399999999999999
Scale.Eevee_Male_Shiny=0.8399999999999999
Scale.Espeon=0.8399999999999999
Scale.Espeon_Shiny=0.8399999999999999
Scale.Espeon_ShinyGold=0.8399999999999999
Scale.Honduran\ White\ Bat=0.6799999999999997
Scale.Sephiroth=1.3200000000000003
Scale.Sylveon=0.8399999999999999
Scale.Sylveon_Shiny=0.8399999999999999
Scale.Tamamo=1.1600000000000001
Scale.Umbreon=0.8399999999999999
Scale.Umbreon_Shiny=0.8399999999999999
Scale.Zorua=0.8399999999999999
Scale.Zorua_Egg=0.8399999999999999
Scale.Zorua_Shiny=0.8399999999999999
Scaling=0.5
Throwing=false
