#Shimeji-ee Configuration Options
<<<<<<< HEAD
#Thu Mar 19 06:16:53 HST 2026
ActiveShimeji=Shimeji
AlwaysShowInformationScreen=false
AlwaysShowShimejiChooser=false
Breeding=true
Environment=generic
Filter=nearest
InformationDismissed=CampfireOFF
InteractiveWindows=a/e/i/o/u/Toy Box/File Explorer/Notepad
InteractiveWindowsBlacklist=
MenuDPI=96
Multiscreen=true
Opacity=1.0
Scaling=0.5
Throwing=true
=======
#Mon Jul 08 21:48:50 WST 2013
InteractiveWindows=Chat/Notepad/Friends/Windows Live Messenger
ActiveShimeji=Shimeji
>>>>>>> fa3d89cbbafb50a8321b1767359aa0a78920f3a3
