#Shimeji-ee Configuration Options
#Mon Apr 13 13:37:09 HST 2026
ActiveShimeji=Shimeji
DisabledBehaviours.Grass=PersonalSpace
InformationDismissed=CampfireOFF
InteractiveWindows=a/e/i/o/u/Toy Box/File Explorer/Notepad
InteractiveWindowsBlacklist=
